import type { AchievementTier, AchievementCategory } from "@/types/database";

export interface AchievementDef {
  key: string;
  name: string;
  description: string;
  icon: string;
  tier: AchievementTier;
  category: AchievementCategory;
  badge_color: string;
  xp_reward: number;
}

export const ACHIEVEMENTS: AchievementDef[] = [
  // ── Explorer ──────────────────────────────────────────────────────────────
  {
    key: "first_step",
    name: "First Step",
    description: "Log your very first check-in.",
    icon: "🍺",
    tier: "bronze",
    category: "explorer",
    badge_color: "#CD7F32",
    xp_reward: 50,
  },
  {
    key: "local_legend",
    name: "Local Legend",
    description: "Check in 10 times at a brewery in your home city.",
    icon: "🏠",
    tier: "silver",
    category: "explorer",
    badge_color: "#C0C0C0",
    xp_reward: 100,
  },
  {
    key: "road_warrior",
    name: "Road Warrior",
    description: "Check in at breweries in 5 different cities.",
    icon: "🚗",
    tier: "silver",
    category: "explorer",
    badge_color: "#C0C0C0",
    xp_reward: 100,
  },
  {
    key: "state_hopper",
    name: "State Hopper",
    description: "Check in at breweries in 3+ states.",
    icon: "🗺️",
    tier: "gold",
    category: "explorer",
    badge_color: "#FFD700",
    xp_reward: 200,
  },
  {
    key: "brewery_tourist_10",
    name: "Brewery Tourist",
    description: "Visit 10 unique breweries.",
    icon: "🏗️",
    tier: "bronze",
    category: "explorer",
    badge_color: "#CD7F32",
    xp_reward: 50,
  },
  {
    key: "craft_pilgrim_25",
    name: "Craft Pilgrim",
    description: "Visit 25 unique breweries.",
    icon: "⛺",
    tier: "silver",
    category: "explorer",
    badge_color: "#C0C0C0",
    xp_reward: 100,
  },
  {
    key: "craft_pilgrim_50",
    name: "Craft Pilgrim II",
    description: "Visit 50 unique breweries.",
    icon: "⛺",
    tier: "gold",
    category: "explorer",
    badge_color: "#FFD700",
    xp_reward: 200,
  },
  {
    key: "craft_pilgrim_100",
    name: "Craft Pilgrim III",
    description: "Visit 100 unique breweries.",
    icon: "⛺",
    tier: "platinum",
    category: "explorer",
    badge_color: "#E5E4E2",
    xp_reward: 500,
  },

  // ── Variety ───────────────────────────────────────────────────────────────
  {
    key: "style_student",
    name: "Style Student",
    description: "Try 5 different beer styles.",
    icon: "📚",
    tier: "bronze",
    category: "variety",
    badge_color: "#CD7F32",
    xp_reward: 50,
  },
  {
    key: "style_scholar",
    name: "Style Scholar",
    description: "Try 10 different beer styles.",
    icon: "🎓",
    tier: "silver",
    category: "variety",
    badge_color: "#C0C0C0",
    xp_reward: 100,
  },
  {
    key: "style_master",
    name: "Style Master",
    description: "Try all major styles: IPA, Stout, Lager, Sour, Porter, Wheat, Pale Ale, Belgian, Saison, and Amber.",
    icon: "🏆",
    tier: "gold",
    category: "variety",
    badge_color: "#FFD700",
    xp_reward: 200,
  },
  {
    key: "hop_head",
    name: "Hop Head",
    description: "Log 20 IPAs.",
    icon: "🌿",
    tier: "silver",
    category: "variety",
    badge_color: "#C0C0C0",
    xp_reward: 100,
  },
  {
    key: "dark_side",
    name: "Dark Side",
    description: "Log 10 stouts or porters.",
    icon: "🌑",
    tier: "bronze",
    category: "variety",
    badge_color: "#CD7F32",
    xp_reward: 50,
  },
  {
    key: "sour_patch",
    name: "Sour Patch",
    description: "Log 10 sours.",
    icon: "🍋",
    tier: "bronze",
    category: "variety",
    badge_color: "#CD7F32",
    xp_reward: 50,
  },
  {
    key: "ipa_lover",
    name: "IPA Lover",
    description: "Log 10 IPAs.",
    icon: "🌿",
    tier: "bronze",
    category: "variety",
    badge_color: "#CD7F32",
    xp_reward: 50,
  },
  {
    key: "sour_head",
    name: "Sour Head",
    description: "Log 5 sours.",
    icon: "🍋",
    tier: "bronze",
    category: "variety",
    badge_color: "#CD7F32",
    xp_reward: 25,
  },
  {
    key: "stout_season",
    name: "Stout Season",
    description: "Log 5 stouts or porters.",
    icon: "🌑",
    tier: "bronze",
    category: "variety",
    badge_color: "#CD7F32",
    xp_reward: 25,
  },
  {
    key: "wheat_king",
    name: "Wheat King",
    description: "Log 10 wheat beers (Wheat, Hefeweizen, Witbier).",
    icon: "🌾",
    tier: "bronze",
    category: "variety",
    badge_color: "#CD7F32",
    xp_reward: 50,
  },
  {
    key: "lager_legend",
    name: "Lager Legend",
    description: "Log 10 lagers (Lager, Pilsner, Kolsch, Helles).",
    icon: "🍺",
    tier: "bronze",
    category: "variety",
    badge_color: "#CD7F32",
    xp_reward: 50,
  },
  {
    key: "domestic_drinker",
    name: "Domestic Drinker",
    description: "Log 5 domestic-style beers (Lager, Pilsner, Cream Ale, Blonde Ale).",
    icon: "🏈",
    tier: "bronze",
    category: "variety",
    badge_color: "#CD7F32",
    xp_reward: 25,
  },
  {
    key: "domestic_devotee",
    name: "Domestic Devotee",
    description: "Log 20 domestic-style beers (Lager, Pilsner, Cream Ale, Blonde Ale).",
    icon: "🇺🇸",
    tier: "silver",
    category: "variety",
    badge_color: "#C0C0C0",
    xp_reward: 100,
  },
  {
    key: "low_and_slow",
    name: "Low & Slow",
    description: "Try 5 session beers under 4.5% ABV.",
    icon: "🐢",
    tier: "bronze",
    category: "variety",
    badge_color: "#CD7F32",
    xp_reward: 50,
  },
  {
    key: "high_flyer",
    name: "High Flyer",
    description: "Try 3 beers over 10% ABV.",
    icon: "🚀",
    tier: "silver",
    category: "variety",
    badge_color: "#C0C0C0",
    xp_reward: 100,
  },

  // ── Quantity ──────────────────────────────────────────────────────────────
  {
    key: "getting_started",
    name: "Getting Started",
    description: "Log 5 total check-ins.",
    icon: "🌱",
    tier: "bronze",
    category: "quantity",
    badge_color: "#CD7F32",
    xp_reward: 50,
  },
  {
    key: "regular",
    name: "Regular",
    description: "Log 25 check-ins.",
    icon: "🪑",
    tier: "bronze",
    category: "quantity",
    badge_color: "#CD7F32",
    xp_reward: 50,
  },
  {
    key: "enthusiast",
    name: "Enthusiast",
    description: "Log 100 check-ins.",
    icon: "⭐",
    tier: "silver",
    category: "quantity",
    badge_color: "#C0C0C0",
    xp_reward: 100,
  },
  {
    key: "veteran",
    name: "Veteran",
    description: "Log 250 check-ins.",
    icon: "🎖️",
    tier: "gold",
    category: "quantity",
    badge_color: "#FFD700",
    xp_reward: 200,
  },
  {
    key: "legend",
    name: "Legend",
    description: "Log 500 check-ins.",
    icon: "👑",
    tier: "platinum",
    category: "quantity",
    badge_color: "#E5E4E2",
    xp_reward: 500,
  },

  // ── Social ────────────────────────────────────────────────────────────────
  {
    key: "better_together",
    name: "Better Together",
    description: "Log a check-in with a friend.",
    icon: "🤝",
    tier: "bronze",
    category: "social",
    badge_color: "#CD7F32",
    xp_reward: 50,
  },
  {
    key: "crew_outing",
    name: "Crew Outing",
    description: "Check in with 3 or more friends at once.",
    icon: "👥",
    tier: "silver",
    category: "social",
    badge_color: "#C0C0C0",
    xp_reward: 100,
  },
  {
    key: "friend_magnet",
    name: "Friend Magnet",
    description: "Have 10 friends on the app.",
    icon: "🧲",
    tier: "silver",
    category: "social",
    badge_color: "#C0C0C0",
    xp_reward: 100,
  },
  {
    key: "trendsetter",
    name: "Trendsetter",
    description: "Be the first of your friends to visit a brewery.",
    icon: "🔭",
    tier: "gold",
    category: "social",
    badge_color: "#FFD700",
    xp_reward: 200,
  },

  // ── Time ──────────────────────────────────────────────────────────────────
  {
    key: "weekend_warrior",
    name: "Weekend Warrior",
    description: "Check in on 4 consecutive weekends.",
    icon: "📅",
    tier: "silver",
    category: "time",
    badge_color: "#C0C0C0",
    xp_reward: 100,
  },
  {
    key: "oktoberfest",
    name: "Oktoberfest",
    description: "Log 5 check-ins in October.",
    icon: "🥨",
    tier: "silver",
    category: "time",
    badge_color: "#C0C0C0",
    xp_reward: 100,
  },
  {
    key: "new_years_hop",
    name: "New Year's Hop",
    description: "Log your first check-in of the year.",
    icon: "🎆",
    tier: "bronze",
    category: "time",
    badge_color: "#CD7F32",
    xp_reward: 50,
  },
  {
    key: "day_tripper",
    name: "Day Tripper",
    description: "Log 5 check-ins in a single day — brewery crawl!",
    icon: "🚌",
    tier: "gold",
    category: "time",
    badge_color: "#FFD700",
    xp_reward: 200,
  },
  {
    key: "streak_master",
    name: "Streak Master",
    description: "Check in at least once per week for 4 consecutive weeks.",
    icon: "🔥",
    tier: "gold",
    category: "time",
    badge_color: "#FFD700",
    xp_reward: 200,
  },
  {
    key: "seven_day_streak",
    name: "7-Day Streak",
    description: "Log a session 7 days in a row. Dedication!",
    icon: "🔥",
    tier: "silver",
    category: "time",
    badge_color: "#C0C0C0",
    xp_reward: 100,
  },
  {
    key: "thirty_day_streak",
    name: "30-Day Streak",
    description: "Log a session 30 days in a row. Legendary commitment.",
    icon: "🔥",
    tier: "gold",
    category: "time",
    badge_color: "#FFD700",
    xp_reward: 200,
  },

  // ── Quality ───────────────────────────────────────────────────────────────
  {
    key: "critics_choice",
    name: "Critic's Choice",
    description: "Give a 5-star rating to 5 different beers.",
    icon: "⭐",
    tier: "bronze",
    category: "quality",
    badge_color: "#CD7F32",
    xp_reward: 50,
  },
  {
    key: "high_standards",
    name: "High Standards",
    description: "Maintain an average rating above 4.0 after 20+ check-ins.",
    icon: "🎯",
    tier: "silver",
    category: "quality",
    badge_color: "#C0C0C0",
    xp_reward: 100,
  },
  {
    key: "photographer",
    name: "Photographer",
    description: "Add photos to 10 check-ins.",
    icon: "📸",
    tier: "bronze",
    category: "quality",
    badge_color: "#CD7F32",
    xp_reward: 50,
  },
  {
    key: "wordsmith",
    name: "Wordsmith",
    description: "Write comments on 20 check-ins.",
    icon: "✍️",
    tier: "silver",
    category: "quality",
    badge_color: "#C0C0C0",
    xp_reward: 100,
  },
];

export const ACHIEVEMENT_MAP = Object.fromEntries(
  ACHIEVEMENTS.map((a) => [a.key, a])
) as Record<string, AchievementDef>;
